import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt


def load_history(metrics_path: Path):
    with open(metrics_path, "r", encoding="utf-8") as file:
        history = json.load(file)

    if not isinstance(history, list) or not history:
        raise ValueError(f"Expected non-empty list in metrics file: {metrics_path}")

    required_keys = {"epoch", "train_loss", "val_loss", "train_acc", "val_acc"}
    for idx, row in enumerate(history, start=1):
        missing = required_keys.difference(row.keys())
        if missing:
            raise ValueError(f"Row {idx} missing keys {sorted(missing)} in {metrics_path}")

    return history


def compute_best_metrics(history):
    best = {
        "best_train_loss": min(history, key=lambda r: r["train_loss"]),
        "best_val_loss": min(history, key=lambda r: r["val_loss"]),
        "best_train_acc": max(history, key=lambda r: r["train_acc"]),
        "best_val_acc": max(history, key=lambda r: r["val_acc"]),
    }
    return {
        "best_train_loss": {
            "value": float(best["best_train_loss"]["train_loss"]),
            "epoch": int(best["best_train_loss"]["epoch"]),
        },
        "best_val_loss": {
            "value": float(best["best_val_loss"]["val_loss"]),
            "epoch": int(best["best_val_loss"]["epoch"]),
        },
        "best_train_acc": {
            "value": float(best["best_train_acc"]["train_acc"]),
            "epoch": int(best["best_train_acc"]["epoch"]),
        },
        "best_val_acc": {
            "value": float(best["best_val_acc"]["val_acc"]),
            "epoch": int(best["best_val_acc"]["epoch"]),
        },
    }


def save_plots(history, output_plot: Path):
    epochs = [row["epoch"] for row in history]
    train_loss = [row["train_loss"] for row in history]
    val_loss = [row["val_loss"] for row in history]
    train_acc = [row["train_acc"] for row in history]
    val_acc = [row["val_acc"] for row in history]

    fig, axes = plt.subplots(2, 2, figsize=(12, 8), constrained_layout=True)

    axes[0, 0].plot(epochs, train_loss, marker="o", linewidth=2)
    axes[0, 0].set_title("Training Loss vs Epoch")
    axes[0, 0].set_xlabel("Epoch")
    axes[0, 0].set_ylabel("Loss")
    axes[0, 0].grid(alpha=0.3)

    axes[0, 1].plot(epochs, val_loss, marker="o", linewidth=2, color="tab:orange")
    axes[0, 1].set_title("Validation Loss vs Epoch")
    axes[0, 1].set_xlabel("Epoch")
    axes[0, 1].set_ylabel("Loss")
    axes[0, 1].grid(alpha=0.3)

    axes[1, 0].plot(epochs, train_acc, marker="o", linewidth=2, color="tab:green")
    axes[1, 0].set_title("Training Accuracy vs Epoch")
    axes[1, 0].set_xlabel("Epoch")
    axes[1, 0].set_ylabel("Accuracy")
    axes[1, 0].grid(alpha=0.3)

    axes[1, 1].plot(epochs, val_acc, marker="o", linewidth=2, color="tab:red")
    axes[1, 1].set_title("Validation Accuracy vs Epoch")
    axes[1, 1].set_xlabel("Epoch")
    axes[1, 1].set_ylabel("Accuracy")
    axes[1, 1].grid(alpha=0.3)

    output_plot.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_plot, dpi=300)
    plt.close(fig)


def save_best_metrics_table(best_metrics, markdown_path: Path, json_path: Path):
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    with open(markdown_path, "w", encoding="utf-8") as file:
        file.write("| Metric | Best Value | Epoch |\n")
        file.write("|---|---:|---:|\n")
        file.write(
            f"| Best Training Loss | {best_metrics['best_train_loss']['value']:.6f} | {best_metrics['best_train_loss']['epoch']} |\n"
        )
        file.write(
            f"| Best Validation Loss | {best_metrics['best_val_loss']['value']:.6f} | {best_metrics['best_val_loss']['epoch']} |\n"
        )
        file.write(
            f"| Best Training Accuracy | {best_metrics['best_train_acc']['value']:.6f} | {best_metrics['best_train_acc']['epoch']} |\n"
        )
        file.write(
            f"| Best Validation Accuracy | {best_metrics['best_val_acc']['value']:.6f} | {best_metrics['best_val_acc']['epoch']} |\n"
        )

    with open(json_path, "w", encoding="utf-8") as file:
        json.dump(best_metrics, file, indent=2)


def parse_args():
    parser = argparse.ArgumentParser(description="Plot training metrics and export best-metrics table.")
    parser.add_argument(
        "--metrics",
        type=str,
        default="outputs/resnet50_baseline/metrics.json",
        help="Path to metrics.json generated by training.",
    )
    parser.add_argument(
        "--plot-out",
        type=str,
        default="outputs/resnet50_baseline/training_curves.png",
        help="Output image path for the 2x2 training curves figure.",
    )
    parser.add_argument(
        "--table-out",
        type=str,
        default="outputs/resnet50_baseline/best_metrics.md",
        help="Output markdown path for best metrics table.",
    )
    parser.add_argument(
        "--best-json-out",
        type=str,
        default="outputs/resnet50_baseline/best_metrics.json",
        help="Output json path for best metrics summary.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    metrics_path = Path(args.metrics)
    plot_out = Path(args.plot_out)
    table_out = Path(args.table_out)
    best_json_out = Path(args.best_json_out)

    history = load_history(metrics_path)
    best_metrics = compute_best_metrics(history)

    save_plots(history, plot_out)
    save_best_metrics_table(best_metrics, table_out, best_json_out)

    print(f"Saved training curves to: {plot_out}")
    print(f"Saved best-metrics markdown table to: {table_out}")
    print(f"Saved best-metrics json to: {best_json_out}")


if __name__ == "__main__":
    main()